WHATSAPP_TOKEN = "EAAQzx8hnetoBPzPOaAZC2ZBG4SilPNfDHZAJM0k6X0JGApBxvsZCTTi5OiLeKicOBbvZBdiqUCpz7bAUQ1mhvOGQwg7ghj6yLy1yoxAZAGxasLYvhlLZBZBcdmMm9E8oyjv7hkrsDjClJOdwEk0AZC8lpoJjc3QFC1tskoxVI2LkymAzZAZAqgcV5HaLDXG8Ga0qzZAkZBwhRsXLw3w1B5vsYdYkG4VeCu8wd0jtA75fwbnMQn36hP5e1TdA1Nek6cZAzHXOrllxSQgzcNT0BWxHdY46HxbKSTQuDoqPZC5CAZDZD"
WHATSAPP_PHONE_NUMBER_ID = "831673940033558"
DESTINATARIOS = "573209989823" 
