[auth]
usuarios = "sebas:Sebitas12, liliana:lili123*, Arauca:Arauca123*"
timeout_minutes = 120

[whatsapp]
# Pega aquí el token temporal que te da Meta (caduca ~24h).
token = "EAAQzx8hnetoBP938FROM7VwDMZCXkyMVqAjUaYVAZBJVzWGIy0mfTVQcSRhWRJn6pbv3zMbyGWqun3IHlipZCAemhkXAq3h7eIZANiEdZBe05fFChZCW8ZBEP8o9cIAqGIDmcs0rssxGwiKHZBoUgEySZCKAfCzaqg8Bj1f0A37wtW5KuDxbMBzNZC2hZCVSyXsrZAH4KRpZBpEyk6EkDfC26WRIZBYvXe4sPzFIFzqjC3satqbwlu2fo6lEUi6LwbBXlk6BZBEWEGkOeJkwZAoaTT4x5yratxTAZA47pTqgQsgZDZD"
# Este es el ID de número de teléfono que ves en la consola de WhatsApp Cloud API.
phone_number_id = "831673940033558"
# Tus destinatarios por defecto (separados por coma). Formato E.164 SIN '+'
destinatarios = "573209989823"