[auth]
usuarios = "sebas:Sebitas12, liliana:lili123*, Arauca:Arauca123*"
timeout_minutes = 120

WHATSAPP_TOKEN = "EAAQzx8hnetoBPZCStiFZCoEILw7ZA76exZBion59H26eIzeGlZALHsfAyhbcocLhubGNXsnIo9TP67KiDciRwcGHuRW0VNwGRY6TZCkZAONXHnUzjCHcXlZBbKeF6MLovYyqITPkXJywaW3hoTObXSkzjXRhkMlT0qURvZAIPYAEZCyZBQBg84pYQCWlS9vt59khCZC39ZART6kOwPS7K6avrY0jELExnxWgyhZCOcAWu2fBklyvZCqLbJ6g7KHNaomqvzbeFjQiCl0yPRJWRyBvuGqaC2wZCowuwHRNeozsvb6j"
WHATSAPP_PHONE_NUMBER_ID = "831673940033558"
DESTINATARIOS = "573209989823"
